# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mPtM_R2aa5kA5H4tJgsB5BeDoU9dmzdM
"""

!pip install scikit-learn

from sklearn.datasets import fetch_california_housing
df = fetch_california_housing()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

df

dataset = pd.DataFrame(df.data)

dataset

dataset.columns=df.feature_names

dataset.head()

#independent and dependent features
X=dataset
y=df.target

y

#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

X_train

#standardizing the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

scaler.fit_transform(X_train)

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
#cross validation
from sklearn.model_selection import cross_val_score

regression=LinearRegression()
regression.fit(X_train,y_train)

mse=cross_val_score(regression,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

mse

np.mean(mse)

regression.predict(X_test)

reg_pred=regression.predict(X_test)

import seaborn as sns
sns.displot(reg_pred-y_test,kind='kde')

from sklearn.metrics import r2_score
score=r2_score(reg_pred,y_test)
score

