# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGLlF4iMVNdekCmVFGXe9aaDupegYK1M
"""

import seaborn as sns
import pandas as pd
import numpy as np

from sklearn import datasets

iris=datasets.load_iris()

print(list(iris.keys()))

print(iris['data'])

print(iris['target'])

print(iris['DESCR'])

X = iris["data"][:,3:]
y = (iris["target"]==2).astype(int)
print(X)
print(y)#doubt

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X,y)

X_new = np.linspace(0,3,1000).reshape(-1,1)#doubt
y_prob = clf.predict_proba(X_new)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.plot(X_new,y_prob[:,1], "g-")
plt.title("virginica")

