# -*- coding: utf-8 -*-
"""Weather Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2UNErDENLVS2mubhn7yFCV69XoiP6tw
"""

import seaborn as sns

import pandas as pd

df=pd.read_csv(r'C:\Users\Shashank Ray\Downloads\1. Weather Data.csv')

df

df.head()

df.shape

df.index

df.dtypes

df.columns

df['Weather'].unique()

df.nunique()

df.count()

df['Weather'].value_counts()

df.info()

#all the unique windspeed values in data
df.head(2)

df.nunique()

df['Wind Speed_km/h'].unique() #ans

#no. of times when the weather is exactly Clear
#filtering
df[df.Weather=='Clear']

#groupby
df.groupby('Weather').get_group('Clear')

#no. of times when wind speed was 4km/h
df.groupby('Wind Speed_km/h').get_group(4)

#null values in data
df.isnull().sum()

#rename column Weather to Weather Condition
df.rename(columns ={'Weather' : 'Weather Condition'}, inplace=True)

df

#mean Visibility
df.Visibility_km.min()

#all instances whn snow was recorded
df[df['Weather Condition'].str.contains('Snow')]

#instances when wind speed is above 24 and visibility is
df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km']==25)]

df.Temp_C.min()

